### PR TITLE
Fix Paludis CONFDIR variable

### PR DESCRIPTION
**Pull request by Krishath**
I couldn't use your script due to that variable.
Fixed it using Paludis' CONFIG_DIR variable.

### CODE REVIEW

**Comment by zaufi** [comment]
What do you mean "can't use use to that variable" ???
after that is not a shell variable... it'll be "expanded" by `cmake`, so final scrip will contain only absolute path depending on chosen `CMAKE_INSTALL_PREFIX`. It is why the script has `.sh.in` extension -- after "rendering" it'll be just `.sh` (i.e. ready to use shell script).

**Comment by Krishath** [comment]
I've done a huge newbie mistake then :)
I've copied the `sh.in` file to `/usr/libexec/paludis-hooks/` and renamed it `.sh` since the `/etc/paludis/bashrc` seemed not to recognize the file (tested it with a `|| echo "file not found"`.
How do I install the file without pulling your whole ebuild then? I'm sorry to have wasted your time.

**Comment by zaufi** [comment]
Sorry, I've though it is "obvious" if the package has `CMakeLists.txt` -- I'll update the `README.md` then...

    $ git clone https://github.com/zaufi/paludis-hooks.git
    $ cd paludis-hooks
    $ cmake  -DCMAKE_INSTALL_PREFIX=/usr ..
    $ sudo make install

that is how the ebuild do that. But one may choose any other prefix to install.

**Comment by Krishath** [comment]
Fixed. Thanks and sorry again.

**Comment by zaufi** [comment]
I wonder why you won't to use the ebuild?

**Pull request closed without merging**
